export const getFileName = (name) => {
  if (!name) return;
  const lastIndex = name.lastIndexOf(".");
  const first = name.slice(0, lastIndex);
  const extension = name.slice(lastIndex + 1);
  return `${first}-thumbnail.${extension}`;
};
export function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(";").shift();
}
export function setCookie(name, value, days) {
  var expires = "";
  if (days) {
    var date = new Date();
    date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
    expires = "; expires=" + date.toUTCString();
  }
  document.cookie = name + "=" + (value || "") + expires + "; path=/";
}
const currencyToCountry = {
  AED: "AE",
  AFN: "AF",
  ALL: "AL",
  AMD: "AM",
  ANG: "NL",
  AOA: "AO",
  ARS: "AR",
  AUD: "AU",
  AWG: "AW",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  BTN: "BT",
  BWP: "BW",
  BYN: "BY",
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUC: "CU",
  CUP: "CU",
  CVE: "CV",
  CZK: "CZ",
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DZD: "DZ",
  EGP: "EG",
  ERN: "ER",
  ETB: "ET",
  EUR: "EU",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LYD: "LY",
  MAD: "MA",
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRU: "MR",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  NGN: "NG",
  NIO: "NI",
  NOK: "NO",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SHP: "SH",
  SLL: "SL",
  SOS: "SO",
  SRD: "SR",
  SSP: "SS",
  STN: "ST",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  UYU: "UY",
  UZS: "UZ",
  VES: "VE",
  VND: "VN",
  VUV: "VU",
  WST: "WS",
  XAF: "CM",
  XCD: "AG",
  XOF: "BJ",
  XPF: "PF",
  YER: "YE",
  ZAR: "ZA",
  ZMW: "ZM",
  // Add more currency-to-country code mappings as needed
};
export const countries = [
  { code: "AD", label: "Andorre", phone: "376" },
  {
    code: "AE",
    label: "Émirats Arabes Unis",
    phone: "971",
  },
  { code: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    label: "Antigua-et-Barbuda",
    phone: "1-268",
  },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albanie", phone: "355" },
  { code: "AM", label: "Arménie", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctique", phone: "672" },
  { code: "AR", label: "Argentine", phone: "54" },
  { code: "AS", label: "Samoa américaines", phone: "1-684" },
  { code: "AT", label: "Autriche", phone: "43" },
  {
    code: "AU",
    label: "Australie",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Îles Åland", phone: "358" },
  { code: "AZ", label: "Azerbaïdjan", phone: "994" },
  {
    code: "BA",
    label: "Bosnie-Herzégovine",
    phone: "387",
  },
  { code: "BB", label: "Barbade", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgique", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgarie", phone: "359" },
  { code: "BH", label: "Bahreïn", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Bénin", phone: "229" },
  { code: "BL", label: "Saint-Barthélemy", phone: "590" },
  { code: "BM", label: "Bermudes", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivie", phone: "591" },
  { code: "BR", label: "Brésil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhoutan", phone: "975" },
  { code: "BV", label: "Île Bouvet", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Biélorussie", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Îles Cocos (Keeling)",
    phone: "61",
  },
  {
    code: "CD",
    label: "Congo, République démocratique du",
    phone: "243",
  },
  {
    code: "CF",
    label: "République centrafricaine",
    phone: "236",
  },
  {
    code: "CG",
    label: "Congo, République du",
    phone: "242",
  },
  { code: "CH", label: "Suisse", phone: "41" },
  { code: "CI", label: "Côte d'Ivoire", phone: "225" },
  { code: "CK", label: "Îles Cook", phone: "682" },
  { code: "CL", label: "Chili", phone: "56" },
  { code: "CM", label: "Cameroun", phone: "237" },
  { code: "CN", label: "Chine", phone: "86" },
  { code: "CO", label: "Colombie", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cap-Vert", phone: "238" },
  { code: "CW", label: "Curaçao", phone: "599" },
  { code: "CX", label: "Île Christmas", phone: "61" },
  { code: "CY", label: "Chypre", phone: "357" },
  { code: "CZ", label: "République tchèque", phone: "420" },
  {
    code: "DE",
    label: "Allemagne",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Danemark", phone: "45" },
  { code: "DM", label: "Dominique", phone: "1-767" },
  {
    code: "DO",
    label: "République dominicaine",
    phone: "1-809",
  },
  { code: "DZ", label: "Algérie", phone: "213" },
  { code: "EC", label: "Équateur", phone: "593" },
  { code: "EE", label: "Estonie", phone: "372" },
  { code: "EG", label: "Égypte", phone: "20" },
  { code: "EH", label: "Sahara occidental", phone: "212" },
  { code: "ER", label: "Érythrée", phone: "291" },
  { code: "ES", label: "Espagne", phone: "34" },
  { code: "ET", label: "Éthiopie", phone: "251" },
  { code: "FI", label: "Finlande", phone: "358" },
  { code: "FJ", label: "Fidji", phone: "679" },
  {
    code: "FK",
    label: "Îles Falkland (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    label: "Micronésie, États fédérés de",
    phone: "691",
  },
  { code: "FO", label: "Îles Féroé", phone: "298" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "Royaume-Uni", phone: "44" },
  { code: "GD", label: "Grenade", phone: "1-473" },
  { code: "GE", label: "Géorgie", phone: "995" },
  { code: "GF", label: "Guyane française", phone: "594" },
  { code: "GG", label: "Guernesey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Groenland", phone: "299" },
  { code: "GM", label: "Gambie", phone: "220" },
  { code: "GN", label: "Guinée", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Guinée équatoriale", phone: "240" },
  { code: "GR", label: "Grèce", phone: "30" },
  {
    code: "GS",
    label: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinée-Bissau", phone: "245" },
  { code: "GY", label: "Guyane", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    label: "Îles Heard et McDonald",
    phone: "672",
  },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatie", phone: "385" },
  { code: "HT", label: "Haïti", phone: "509" },
  { code: "HU", label: "Hongrie", phone: "36" },
  { code: "ID", label: "Indonésie", phone: "62" },
  { code: "IE", label: "Irlande", phone: "353" },
  { code: "IL", label: "Israël", phone: "972" },
  { code: "IM", label: "Île de Man", phone: "44" },
  { code: "IN", label: "Inde", phone: "91" },
  {
    code: "IO",
    label: "Territoire britannique de l'océan Indien",
    phone: "246",
  },
  { code: "IQ", label: "Irak", phone: "964" },
  {
    code: "IR",
    label: "Iran, République islamique d'",
    phone: "98",
  },
  { code: "IS", label: "Islande", phone: "354" },
  { code: "IT", label: "Italie", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaïque", phone: "1-876" },
  { code: "JO", label: "Jordanie", phone: "962" },
  {
    code: "JP",
    label: "Japon",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kirghizistan", phone: "996" },
  { code: "KH", label: "Cambodge", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comores", phone: "269" },
  {
    code: "KN",
    label: "Saint-Christophe-et-Niévès",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "Corée, République populaire démocratique de",
    phone: "850",
  },
  { code: "KR", label: "Corée, République de", phone: "82" },
  { code: "KW", label: "Koweït", phone: "965" },
  { code: "KY", label: "Îles Caïmans", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    label: "République démocratique populaire lao",
    phone: "856",
  },
  { code: "LB", label: "Liban", phone: "961" },
  { code: "LC", label: "Sainte-Lucie", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Libéria", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lituanie", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Lettonie", phone: "371" },
  { code: "LY", label: "Libye", phone: "218" },
  { code: "MA", label: "Maroc", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  {
    code: "MD",
    label: "Moldavie, République de",
    phone: "373",
  },
  { code: "ME", label: "Monténégro", phone: "382" },
  {
    code: "MF",
    label: "Saint-Martin (partie française)",
    phone: "590",
  },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Îles Marshall", phone: "692" },
  {
    code: "MK",
    label: "Macédoine, l'Ex-République yougoslave de",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolie", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  {
    code: "MP",
    label: "Îles Mariannes du Nord",
    phone: "1-670",
  },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritanie", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malte", phone: "356" },
  { code: "MU", label: "Maurice", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexique", phone: "52" },
  { code: "MY", label: "Malaisie", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibie", phone: "264" },
  { code: "NC", label: "Nouvelle-Calédonie", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Île Norfolk", phone: "672" },
  { code: "NG", label: "Nigéria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Pays-Bas", phone: "31" },
  { code: "NO", label: "Norvège", phone: "47" },
  { code: "NP", label: "Népal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niué", phone: "683" },
  { code: "NZ", label: "Nouvelle-Zélande", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Pérou", phone: "51" },
  { code: "PF", label: "Polynésie française", phone: "689" },
  { code: "PG", label: "Papouasie-Nouvelle-Guinée", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Pologne", phone: "48" },
  {
    code: "PM",
    label: "Saint-Pierre-et-Miquelon",
    phone: "508",
  },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Porto Rico", phone: "1" },
  {
    code: "PS",
    label: "Palestine, État de",
    phone: "970",
  },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palaos", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "La Réunion", phone: "262" },
  { code: "RO", label: "Roumanie", phone: "40" },
  { code: "RS", label: "Serbie", phone: "381" },
  { code: "RU", label: "Fédération de Russie", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Arabie saoudite", phone: "966" },
  { code: "SB", label: "Îles Salomon", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Soudan", phone: "249" },
  { code: "SE", label: "Suède", phone: "46" },
  { code: "SG", label: "Singapour", phone: "65" },
  { code: "SH", label: "Sainte-Hélène", phone: "290" },
  { code: "SI", label: "Slovénie", phone: "386" },
  {
    code: "SJ",
    label: "Svalbard et Île Jan Mayen",
    phone: "47",
  },
  { code: "SK", label: "Slovaquie", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "Saint-Marin", phone: "378" },
  {
    code: "SN",
    label: "Sénégal",
    phone: "221",
  },
  { code: "SO", label: "Somalie", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "Soudan du Sud", phone: "211" },
  { code: "ST", label: "Sao Tomé et Principe", phone: "239" },
  { code: "SV", label: "El Salvador", phone: "503" },
  { code: "SX", label: "Saint-Martin (partie néerlandaise)", phone: "1-721" },
  { code: "SY", label: "République arabe syrienne", phone: "963" },
  { code: "SZ", label: "Swaziland", phone: "268" },
  { code: "TC", label: "Îles Turques-et-Caïques", phone: "1-649" },
  { code: "TD", label: "Tchad", phone: "235" },
  { code: "TF", label: "Terres australes françaises", phone: "262" },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thaïlande", phone: "66" },
  { code: "TJ", label: "Tadjikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkménistan", phone: "993" },
  { code: "TN", label: "Tunisie", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turquie", phone: "90" },
  { code: "TT", label: "Trinité-et-Tobago", phone: "1-868" },
  { code: "TV", label: "Tuvalu", phone: "688" },
  { code: "TW", label: "Taïwan", phone: "886" },
  { code: "TZ", label: "Tanzanie, République unie de", phone: "255" },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Ouganda", phone: "256" },
  { code: "UM", label: "Îles mineures éloignées des États-Unis", phone: "1" },
  { code: "US", label: "États-Unis", phone: "1" },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Ouzbékistan", phone: "998" },
  {
    code: "VA",
    label: "Saint-Siège (État de la Cité du Vatican)",
    phone: "39",
  },
  { code: "VC", label: "Saint-Vincent-et-les-Grenadines", phone: "1-784" },
  { code: "VE", label: "Venezuela", phone: "58" },
  { code: "VG", label: "Îles Vierges britanniques", phone: "1-284" },
  { code: "VI", label: "Îles Vierges des États-Unis", phone: "1-340" },
  { code: "VN", label: "Viêt Nam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis-et-Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "YE", label: "Yémen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "Afrique du Sud", phone: "27" },
  { code: "ZM", label: "Zambie", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export default countries;
export function getCountryCode(currencyCode) {
  return currencyToCountry[currencyCode] || "Unknown";
}
export const getPriceValidUntil = () => {
  let currentDate = new Date();
  currentDate.setDate(currentDate.getDate() + 1);
  return currentDate.toISOString().split("T")[0];
};

export const tempData = [
  {
    id: 0,
    img: "logo.png",
    title:
      "Change et Or Bastille : Votre Nouveau Partenaire pour le Change de Devises et l'Investissement en Or",
    desc: "Chez Change et Or Bastille, nous savons que chaque transaction compte. Notre équipe dédiée s'efforce de fournir des taux de change compétitifs et des options d'investissement en or fiables qui répondent à vos besoins financiers. Que vous prévoyiez un voyage à l'étranger ou que vous cherchiez à investir dans un métal précieux, nous avons conçu nos services pour vous apporter confort et confiance.",
  },
  {
    id: 1,
    img: "img2.png",
    title:
      "Changez vos Devises en Ligne en toute Simplicité avec Change et Or Bastille",
    desc: "Voyager à l'étranger devient plus facile avec Change et Or Bastille. Nous nous engageons à offrir les meilleurs taux de change du marché, avec un service de livraison rapide et sécurisé. Quelle que soit la destination de votre voyage, nous proposons un large choix de devises pour répondre à vos besoins.",
  },
  {
    id: 2,
    img: "gold.png",
    title:
      "Investissez dans l'Or en toute Confiance avec Change et Or Bastille",
    desc: "L'or a toujours été considéré comme une valeur refuge pour les investisseurs. Chez Change et Or Bastille, nous vous proposons des options d'investissement en or fiables qui correspondent à vos objectifs financiers. Qu'il s'agisse de lingots d'or ou de pièces d'or, nous offrons des tarifs compétitifs et des options de livraison sûres pour votre investissement.",
  },
];

export function translateOrderStatusToFrench(status) {
  const statusTranslations = {
    "Not Proccessed": "Non traité",
    Preparing: "En préparation",
    Delivering: "En cours de livraison",
    Delivered: "Livré",
    Canceled: "Annulé",
  };

  return statusTranslations[status] || "Translation not available";
}

export function translatePaymentStatusToFrench(status) {
  const statusTranslations = {
    "Not Proccessed": "Non traité",
    Paid: "Payé",
    "Not Paid": "Non payé",
  };

  return statusTranslations[status] || "Translation not available";
}
